(create-elements!
  (rectangle '(id button x 300 y 100 width 200 height 200)
    (mouse-area (list 'width '(bind (observe 'parent 'width) identity)
                      'height '(bind (observe 'parent 'height) identity)
                      'color '(0 0 255)
                      'on-mouse-down (lambda (b x y) 
                        (set-prop! (find-element 'button) 'color '(0 0 255)))
                      'on-mouse-up (lambda (b x y) 
                        (set-prop! (find-element 'button) 'color '(255 0 255)))
                      'on-mouse-move (lambda (sx sy dx dy) 
                        (set-prop! (find-element 'button) 'color '(255 255 0)))
                      'on-mouse-enter (lambda (sx sy dx dy) 
                        (set-prop! (find-element 'inner) 'color '(255 0 0)))
                      'on-mouse-exit (lambda (sx sy dx dy) 
                         (set-prop! (find-element 'inner) 'color '(0 255 0))))
      (rectangle '(id inner x 75 y 75 width 50 height 50 color (0 0 0))))))
    